version: '3.7'

services:
  web-api:
    build: ./src
    command: uvicorn app.main:app --reload --port 8000 --host 0.0.0.0 --workers 1
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8001:8000"
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev

volumes:
  postgres_data:
